// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinSon;

namespace MinSon.Migrations
{
    [DbContext(typeof(MinSonDBContext))]
    [Migration("20220302145037_showcaseproduct")]
    partial class showcaseproduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MinSon.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("birthYear")
                        .HasColumnType("int");

                    b.Property<string>("imageUrl_Item1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl_Item2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("owners")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("showcase_Item1_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("showcase_Item1_Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("showcase_Item2_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("showcase_Item2_Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("webbImage_Item1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("webbImage_Item2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("webbUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("MinSon.Domain.Entities.ZeldaQuote", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("character")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("quote")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("zeldaQuotes");
                });
#pragma warning restore 612, 618
        }
    }
}
